%ele range =  25.2012	  34.3775   	43.5538	
ele = [34.3775     28.6479    38.3211  31.5127  42.3989  31.5127 39.4768];

%bearing	range =   93.2866	103     112.7134
ang = [103.1324    108.8620   111.3211  96.2569  100.2676  105.9972 107.0858];
% plot(ang,ele,'-rO','LineWidth',10,...
%     'MarkerEdgeColor','r',...
%     'MarkerFaceColor','r',...
%     'MarkerSize',5)
 plot(ang(1),ele(1),'b^','LineWidth',2,...
                       'MarkerEdgeColor','b',...
                       'MarkerFaceColor','b',...
                       'MarkerSize',10)
 hold on
  plot(ang(2),ele(2),'k^','LineWidth',2,...
                       'MarkerEdgeColor','k',...
                       'MarkerFaceColor','k',...
                       'MarkerSize',10)
 hold on
  plot(ang(3),ele(3),'k^','LineWidth',2,...
                       'MarkerEdgeColor','k',...
                       'MarkerFaceColor','k',...
                       'MarkerSize',10)
 hold on
  plot(ang(4),ele(4),'k^','LineWidth',2,...
                       'MarkerEdgeColor','k',...
                       'MarkerFaceColor','k',...
                       'MarkerSize',10)
 hold on
  plot(ang(5),ele(5),'k^','LineWidth',2,...
                       'MarkerEdgeColor','k',...
                       'MarkerFaceColor','k',...
                       'MarkerSize',10)
 hold on
  plot(ang(6),ele(6),'k^','LineWidth',2,...
                       'MarkerEdgeColor','k',...
                       'MarkerFaceColor','k',...
                       'MarkerSize',10)
 hold on
  plot(ang(7),ele(7),'k^','LineWidth',2,...
                       'MarkerEdgeColor','k',...
                       'MarkerFaceColor','k',...
                       'MarkerSize',10)
                   hold on
%   plot(ang(8),ele(8),'k^','LineWidth',2,...
%                        'MarkerEdgeColor','k',...
%                        'MarkerFaceColor','k',...
%                        'MarkerSize',10)
 legend('Target originated measurement','Noise originated measurement')
ylabel('elevation (m)');
xlabel('bearing (degrees)');